<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Phalcon PHP Framework</title>
    </head>
    <body>
        <div class="container">
            <h1>Error Encountered :(</h1>
            <em>This page is located in views/500.phtml</em>
            <div style="border: 1px wolid darkgrey; background-color: lightgrey; padding: 10px; display: <?php echo $stacktrace ? '' : 'none'?>;">
                <p>
                    <?php echo $errorMsg; ?>
                </p>
            </div>
        </div>
    </body>
</html>
